// /lib/countries.ts
const countries: { [code: string]: string } = {
    "sq-AL": "Albania",
    "am-ET": "Amharic",
    "ar-SA": "Arabic",
    "hy-AM": "Armenian",
    "az-AZ": "Azeri",
    "be-BY": "Belarusian",
    "bs-BA": "Bosnia and Herzegovina",
    "bg-BG": "Bulgarian",
    "ca-ES": "Catalan",
    "zh-CN": "Chinese",
    "hr-HR": "Croatian",
    "cs-CZ": "Czech",
    "da-DK": "Danish",
    "nl-BE": "Dutch(Belgium)",
    "nl-NL": "Dutch(Netherlands)",
    "dv-MV": "Divehi(Maldives)",
    "en-GB": "English(UK)",
    "en-US": "English(US)",
    "et-EE": "Estonian",
    "fr-GF": "French (Guiana)",
    "fr-PF": "French (Polynesia)",
    "fr-TF": "French Southern Territories",
    "de-DE": "German",
    "el-GR": "Greek",
    "ha-NG": "Hausa",
    "he-IL": "Hebrew",
    "hi-IN": "Hindi",
    "hu-HU": "Hungarian",
    "is-IS": "Icelandic",
    "ig-NG": "Igbo",
    "id-ID": "Indonesia",
    "it-IT": "Italian",
    "ja-JP": "Japanese",
    "kr-NG": "Kanuri",
    "kk-KZ": "Kazakh",
    "km-KH": "Khmer",
    "ki-KE": "Kikuyu",
    "rw-RW": "Kinyarwanda",
    "kg-CG": "kongo",
    "ko-KR": "Korea",
    "lo-LA": "Lao",
    "ln-CG": "Lingala",
    "lt-LT": "Lithuanian",
    "lb-LU": "Luxembourgish",
    "mk-MK": "Macedonian",
    "mg-MG": "Malagasy",
    "ms-MY": "Malay",
    "ml-IN": "Malayalam",
    "mt-MT": "Maltese",
    "mi-NZ": "Maori",
    "mh-MH": "Marshallese",
    "mn-MN": "Mongolian",
    "ne-IN": "Nepali",
    "no-NO": "Norwagian",
    "ny-MZ": "Nyanja",
    "ro-RO": "Romanian",
    "rm-SZ": "Romansh",
    "ru-RU": "Russian",
    "sg-CF": "Sango",
    "sr-RS": "Serbian",
    "sk-SK": "Slovak",
    "sl-SI": "Slovenian",
    "so-SO": "Somalia",
    "st-LS": "Sotho",
    "es-ES": "Spanish",
    "su-ID": "Sundanese",
    "sv-SE": "Swedish",
    "th-TH": "Thai",
    "tr-TR": "Turkish",
    "tk-TM": "Turkmen",
    "GH": "Twi",
    "uk-UA": "Ukrainian",
    "uz-UZ": "Uzbek",
    "vi-VN": "Vietnamese",
    "cy-GB": "Welsh",
    "wo-SN": "Wolof",
    "xh-ZA": "Xhosa",
    "yo-NG": "Yoruba",
    "sn-ZW": "Zimbabwe" 
  };
  
  export default countries;
  